language: java
jdk:
- oraclejdk8
script:
- ./mvnw clean package
after_success:
- ./mvnw clean test jacoco:report coveralls:report
install: true
cache:
  directories:
  - ~/.m2/repository
  - ~/.m2/wrapper